# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.1.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.0
                3.1.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.1
                3.1.2=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.2
                3.2.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.0
                3.2.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.1
                3.2.3=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.1.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.0
                3.1.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.1
                3.1.2=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.2
                3.2.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.0
                3.2.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.1
                3.2.3=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.1.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.0
                3.1.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.1
                3.1.2=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.2
                3.2.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.0
                3.2.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.1
                3.2.3=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.1.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.0
                3.1.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.1
                3.1.2=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.1.2
                3.2.0=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.0
                3.2.1=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.1
                3.2.3=registry.sighup.io/fury/strimzi/kafka:0.31.1-kafka-3.2.3
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: registry.sighup.io/fury/strimzi/operator:0.31.1
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: registry.sighup.io/fury/strimzi/operator:0.31.1
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: registry.sighup.io/fury/strimzi/operator:0.31.1
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: registry.sighup.io/fury/strimzi/kafka-bridge:0.22.1
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: registry.sighup.io/fury/strimzi/jmxtrans:0.31.1
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: registry.sighup.io/fury/strimzi/kaniko-executor:0.31.1
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: registry.sighup.io/fury/strimzi/maven-builder:0.31.1